language: node_js
matrix:
  include:
    - os: linux
      node_js: 12
      before_install:
        - npm install request

install:
- npm install

before_script:
  - npx babel ./server --out-dir dist-server --copy-files

after_script:
  - npm run test && npx npx istanbul-coveralls